### PR TITLE
Update email templates at startup

### PR DESCRIPTION
**Pull request by dineshdb**
Impact: **minor**
Type: **bugfix**

## Issue
Currently, if we upgrade templates version or add new templates, they are not registered because templates are registered only at _shopCreate_ event.

## Solution
With this change, any new updates will be picked up.

### CODE REVIEW

**Comment by Akarshit** [comment]
@dineshdb Thanks for the PR, looking at it I see an issue. With your change the email templates won't be added when the admin creates a shop for the first time. They would only be added on a restart.
Maybe a better approach would be to have the templates update both on shop creation *and* on restart.

**Comment by dineshdb** [comment]
Ah, I see. The fix should be to not remove the event listener for shop creation. Do you want me to path this PR?

**Comment by Akarshit** [comment]
Yes it would be to keep the event listener and also have the code that you added. It would be awesome if you can patch the PR. I will get it merged ASAP after that.

**Comment by Akarshit** [comment]
Looks good to me.

**Review by Akarshit — APPROVED** [review]

**Pull request merged**
